export {default as Navbar} from './Navbar'
export {default as LandingPage} from './LandingPage'
export {default as About} from './About'
export {default as Technologies} from './Technologies'
export {default as SkillCard} from './SkillCard'
export {default as Projects} from './Projects'
export {default as ProjectCard} from './ProjectCard'
export {default as Contact} from './Contact'