export {default as Navbar} from './Navbar'
export {default as LandingPage} from './LandingPage'
export {default as About} from './About'
export {default as Technologies} from './Technologies'
export {default as SkillCard} from './SkillCard'